services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: mysql
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db

volumes:
  mysql-volume:
    driver: local